<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            [
                'type' => 'static',
                'option' => 'infoModVersion',
                'value' => '1.0.0',
                'constant' => 'INFO_MOD_VERSION',
                'category' => 'system',
                'description' => 'Версия движка сайта',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'siteLayout',
                'value' => 'Default',
                'constant' => 'SITE_LAYOUT',
                'category' => 'public',
                'description' => 'Шаблон публичной части сайта',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'checkbox',
                'option' => 'downtimeSite',
                'value' => 'false',
                'constant' => 'DOWNTIME_SITE',
                'category' => 'public',
                'description' => 'Включение/Выключение публичной части сайта на технические работы',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'widgetHexColor',
                'value' => '155e75',
                'constant' => 'WIDGET_HEX_COLOR',
                'category' => 'admin',
                'description' => 'Задаёт цвет панелей сайдбара и виджетов',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'float',
                'option' => 'widgetOpacity',
                'value' => '0.99',
                'constant' => 'WIDGET_OPACITY',
                'category' => 'admin',
                'description' => 'Задаёт прозрачность цвета панелей сайдбара и виджетов',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountRubrics',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_RUBRICS',
                'category' => 'admin',
                'description' => 'Показывать количество Рубрик в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortRubrics',
                'value' => 'sort',
                'constant' => 'ADMIN_SORT_RUBRICS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Рубрик по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountArticles',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_ARTICLES',
                'category' => 'admin',
                'description' => 'Показывать количество Постов в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortArticles',
                'value' => 'sort',
                'constant' => 'ADMIN_SORT_ARTICLES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Постов по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountTags',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_TAGS',
                'category' => 'admin',
                'description' => 'Показывать количество Тегов в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortTags',
                'value' => 'name',
                'constant' => 'ADMIN_SORT_TAGS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Тегов по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountComments',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_COMMENTS',
                'category' => 'admin',
                'description' => 'Показывать количество Комментариев в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortComments',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_COMMENTS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Комментариев по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountBanners',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_BANNERS',
                'category' => 'admin',
                'description' => 'Показывать количество Баннеров в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortBanners',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_BANNERS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Баннеров по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountVideos',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_VIDEOS',
                'category' => 'admin',
                'description' => 'Показывать количество Видео в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortVideos',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_VIDEOS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Видео по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountInstructors',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_INSTRUCTORS',
                'category' => 'admin',
                'description' => 'Показывать количество Преподавателей в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortInstructors',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_INSTRUCTORS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Преподавателей по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountLearningCategories',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_LEARNING_CATEGORIES',
                'category' => 'admin',
                'description' => 'Показывать количество Категорий Курсов в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortLearningCategories',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_LEARNING_CATEGORIES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Категорий Курсов по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountHashtags',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_HASHTAGS',
                'category' => 'admin',
                'description' => 'Показывать количество Тегов обучения в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortHashtags',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_HASHTAGS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Тегов обучения по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountLearningCourses',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_LEARNING_COURSES',
                'category' => 'admin',
                'description' => 'Показывать количество Курсов обучения в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortLearningCourses',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_LEARNING_COURSES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Курсов обучения по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountLearningModules',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_LEARNING_MODULES',
                'category' => 'admin',
                'description' => 'Показывать количество Модулей обучения в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortLearningModules',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_LEARNING_MODULES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Модулей обучения по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountLearningLessons',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_LEARNING_LESSONS',
                'category' => 'admin',
                'description' => 'Показывать количество Уроков обучения в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortLearningLessons',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_LEARNING_LESSONS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Уроков обучения по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountAssignments',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_ASSIGNMENTS',
                'category' => 'admin',
                'description' => 'Показывать количество Заданий для обучения в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortAssignments',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_ASSIGNMENTS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Заданий для обучения по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountCourseSchedules',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_COURSE_SCHEDULES',
                'category' => 'admin',
                'description' => 'Показывать количество потоков расписания в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortCourseSchedules',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_COURSE_SCHEDULES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у потоков расписания по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountCohortEnrollments',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_COHORT_ENROLLMENTS',
                'category' => 'admin',
                'description' => 'Показывать количество записей на потоки в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortCohortEnrollments',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_COHORT_ENROLLMENTS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у записей на потоки по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountEnrollments',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_ENROLLMENTS',
                'category' => 'admin',
                'description' => 'Показывать количество зачислений на потоки в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortEnrollments',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_ENROLLMENTS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у зачислений на потоки по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountQuizQuestions',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_QUIZ_QUESTIONS',
                'category' => 'admin',
                'description' => 'Показывать количество вопросов викторин в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortQuizQuestions',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_QUIZ_QUESTIONS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у вопросов викторин по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountQuizAnswers',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_QUIZ_ANSWERS',
                'category' => 'admin',
                'description' => 'Показывать количество ответов викторин в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortQuizAnswers',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_QUIZ_ANSWERS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у ответов викторин по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountQuizAttempts',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_QUIZ_ATTEMPTS',
                'category' => 'admin',
                'description' => 'Показывать количество прохождений викторин в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortQuizAttempts',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_QUIZ_ATTEMPTS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у прохождений викторин по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountQuizAttemptItems',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_QUIZ_ATTEMPT_ITEMS',
                'category' => 'admin',
                'description' => 'Показывать количество ответов викторин в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortQuizAttemptItems',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_QUIZ_ATTEMPT_ITEMS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у ответов викторин по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountBundles',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_BUNDLES',
                'category' => 'admin',
                'description' => 'Показывать количество Бандлов в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortBundles',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_BUNDLES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Бандлов по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountCurrencies',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_CURRENCIES',
                'category' => 'admin',
                'description' => 'Показывать количество Валют в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortCurrencies',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_CURRENCIES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Валют по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountOrders',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_ORDERS',
                'category' => 'admin',
                'description' => 'Показывать количество Заказов в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortOrders',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_ORDERS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Заказов по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountCoursePrices',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_COURSE_PRICES',
                'category' => 'admin',
                'description' => 'Показывать количество Прайсов курсов в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortCoursePrices',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_COURSE_PRICES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Прайсов курсов по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountBundlePrices',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_BUNDLE_PRICES',
                'category' => 'admin',
                'description' => 'Показывать количество Прайсов наборов курсов в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortBundlePrices',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_BUNDLE_PRICES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Прайсов наборов курсов по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountSubscriptionPlans',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_SUBSCRIPTION_PLANS',
                'category' => 'admin',
                'description' => 'Показывать количество Тарифных планов в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortSubscriptionPlans',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_SUBSCRIPTION_PLANS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Тарифных планов по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountUsers',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_USERS',
                'category' => 'admin',
                'description' => 'Показывать количество Пользователей в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortUsers',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_USERS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Пользователей по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountRoles',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_ROLES',
                'category' => 'admin',
                'description' => 'Показывать количество Релей в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortRoles',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_ROLES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Релей по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountPermissions',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_PERMISSIONS',
                'category' => 'admin',
                'description' => 'Показывать количество Разрешений в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortPermissions',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_PERMISSIONS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Разрешений по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountCategories',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_CATEGORIES',
                'category' => 'admin',
                'description' => 'Показывать количество Категорий в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortCategories',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_CATEGORIES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Категорий по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountMarketCompanies',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_MARKET_COMPANIES',
                'category' => 'admin',
                'description' => 'Показывать количество Компаний в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortMarketCompanies',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_MARKET_COMPANIES',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Компаний по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountMarketStorefronts',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_MARKET_STOREFRONTS',
                'category' => 'admin',
                'description' => 'Показывать количество Витрин в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortMarketStorefronts',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_MARKET_STOREFRONTS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Витрин по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'AdminCountSettings',
                'value' => '20',
                'constant' => 'ADMIN_COUNT_SETTINGS',
                'category' => 'admin',
                'description' => 'Показывать количество Параметров в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSortSettings',
                'value' => 'id',
                'constant' => 'ADMIN_SORT_SETTINGS',
                'category' => 'admin',
                'description' => 'Сортировка по полю у Параметров по умолчанию в таблице Панели Администратора',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'PublicLightBackgroundColor',
                'value' => 'bg-slate-50',
                'constant' => 'PUBLIC_LIGHT_BACKGROUND_COLOR',
                'category' => 'public',
                'description' => 'Класс Tailwind CSS фонового цвета светлого режима',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'PublicDarkBackgroundColor',
                'value' => 'bg-blue-800',
                'constant' => 'PUBLIC_DARK_BACKGROUND_COLOR',
                'category' => 'public',
                'description' => 'Класс Tailwind CSS фонового цвета тёмного режима',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'PublicHeaderLightBackgroundColor',
                'value' => 'bg-blue-800',
                'constant' => 'PUBLIC_HEADER_LIGHT_BACKGROUND_COLOR',
                'category' => 'public',
                'description' => 'Класс Tailwind CSS цвета светлого режима для header',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'PublicHeaderDarkBackgroundColor',
                'value' => 'bg-slate-800',
                'constant' => 'PUBLIC_HEADER_DARK_BACKGROUND_COLOR',
                'category' => 'public',
                'description' => 'Класс Tailwind CSS цвета тёмного режима для header',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'checkbox',
                'option' => 'ViewLeftColumn',
                'value' => 'true',
                'constant' => 'VIEW_LEFT_COLUMN',
                'category' => 'public',
                'description' => 'Включение/Выключение левой колонки в публичной части',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'checkbox',
                'option' => 'ViewRightColumn',
                'value' => 'true',
                'constant' => 'VIEW_RIGHT_COLUMN',
                'category' => 'public',
                'description' => 'Включение/Выключение правой колонки в публичной части',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'PublicViewArticle',
                'value' => 'grid',
                'constant' => 'PUBLIC_VIEW_ARTICLE',
                'category' => 'public',
                'description' => 'Вид показа блоков Статей в секциях grid/horizontal',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'number',
                'option' => 'PublicCountArticle',
                'value' => '3',
                'constant' => 'PUBLIC_COUNT_ARTICLE',
                'category' => 'public',
                'description' => 'Показывать количество Статей в секциях по умолчанию',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarDarkColor',
                'value' => 'bg-gray-700',
                'constant' => 'ADMIN_SIDEBAR_DARK_COLOR',
                'category' => 'admin',
                'description' => 'Класс Tailwind CSS цвета тёмного режима для левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarLightColor',
                'value' => 'bg-cyan-800',
                'constant' => 'ADMIN_SIDEBAR_LIGHT_COLOR',
                'category' => 'admin',
                'description' => 'Класс Tailwind CSS цвета светлого режима для левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarDarkText',
                'value' => 'text-slate-200',
                'constant' => 'ADMIN_SIDEBAR_DARK_TEXT',
                'category' => 'admin',
                'description' => 'Класс Tailwind CSS цвета текста тёмного режима для левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarLightText',
                'value' => 'text-slate-200',
                'constant' => 'ADMIN_SIDEBAR_LIGHT_TEXT',
                'category' => 'admin',
                'description' => 'Класс Tailwind CSS цвета текста светлого режима для левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarDarkHoverText',
                'value' => 'text-red-300',
                'constant' => 'ADMIN_SIDEBAR_DARK_HOVER_TEXT',
                'category' => 'admin',
                'description' => 'Класс Tailwind CSS цвета при наведении на текст в тёмном режиме левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarLightHoverText',
                'value' => 'text-red-300',
                'constant' => 'ADMIN_SIDEBAR_LIGHT_HOVER_TEXT',
                'category' => 'admin',
                'description' => 'Класс Tailwind CSS цвета при наведении на текст в светлом режиме левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarDarkActiveText',
                'value' => 'text-yellow-200',
                'constant' => 'ADMIN_SIDEBAR_DARK_ACTIVE_TEXT',
                'category' => 'admin',
                'description' => 'Класс Tailwind CSS цвета активной ссылки в тёмном режиме левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],
            [
                'type' => 'string',
                'option' => 'AdminSidebarLightActiveText',
                'value' => 'text-yellow-200',
                'constant' => 'ADMIN_SIDEBAR_LIGHT_ACTIVE_TEXT',
                'category' => 'admin',
                'description' => 'Класс Tailwind CSS цвета активной ссылки в светлом режиме левого Сайдбара',
                'activity' => true,
                'sort' => 0,
            ],

            // Добавьте остальные параметры
        ];

        // Если по колонке `option` уже есть уникальный индекс — этого достаточно:
        //DB::table('settings')->insertOrIgnore($settings);

        // Если вдруг уникального индекса по `option` НЕТ (и добавлять миграцией пока не хочешь),
        // замени строку выше на этот блок-фильтр:

        $existing = DB::table('settings')->pluck('option')->all();
        $map = array_flip($existing);
        $toInsert = array_values(array_filter($settings, fn($row) => !isset($map[$row['option']])));

        if ($toInsert) {
            DB::table('settings')->insert($toInsert);
        }
    }
}
